ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "paymentDetails" JSONB;
ALTER TABLE "Trade" ADD COLUMN IF NOT EXISTS "paymentInstructions" JSONB;
ALTER TABLE "Trade" ADD COLUMN IF NOT EXISTS "paymentProof" JSONB;
ALTER TABLE "Trade" ADD COLUMN IF NOT EXISTS "sellerPaymentConfirmedAt" TIMESTAMP(3);
